- hosts: all
  connection: local
  vars:
    proxy_env:
      no_proxy: "localhost,127.0.0.1,web.bkinney.lan"
      NO_PROXY: "localhost,127.0.0.1,web.bkinney.lan"

  environment:
    no_proxy: "web.bkinney.lan"
    NO_PROXY: "web.bkinney.lan"
